tap "bfontaine/command-not-found"
tap "bramstein/webfonttools"
tap "caskroom/cask"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "hhvm/hhvm"
tap "homebrew/apache"
tap "homebrew/binary"
tap "homebrew/bundle"
tap "homebrew/completions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/nginx"
tap "homebrew/php"
tap "homebrew/services"
tap "homebrew/versions"
tap "teslamint/devel"
tap "vitorgalvao/tiny-scripts"
cask "xquartz"
brew "ack"
brew "aircrack-ng"
brew "bash"
brew "bash-completion@2"
brew "binutils"
brew "p7zip"
brew "xz"
brew "binwalk"
brew "cifer"
brew "coreutils"
brew "dark-mode"
brew "dex2jar"
brew "dns2tcp"
brew "doxygen"
brew "fcrackzip"
brew "findutils"
brew "foremost"
brew "talloc"
brew "freeradius-server"
brew "fzf"
brew "gengetopt"
brew "git"
brew "git-lfs"
brew "git-when-merged"
brew "gnu-getopt"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "grep"
brew "hashpump"
brew "hydra"
brew "imagemagick", args: ["with-webp"]
brew "john"
brew "json-c"
brew "knock"
brew "libidn"
brew "libxml2"
brew "libyubikey"
brew "lua"
brew "lynx"
brew "mas"
brew "minicom"
brew "mono"
brew "moreutils"
brew "ncurses"
brew "nano"
brew "narwhal"
brew "netpbm"
brew "nmap"
brew "node"
brew "openssh"
brew "ykclient"
brew "ykpers"
brew "pam_yubico"
brew "pigz"
brew "pngcheck"
brew "pv"
brew "qt"
brew "quilt"
brew "rename"
brew "ringojs"
brew "screen"
brew "socat"
brew "speedtest_cli"
brew "sqlmap"
brew "squashfs"
brew "ssh-copy-id"
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "testssl"
brew "tmux"
brew "tree"
brew "ucspi-tcp"
brew "vbindiff"
brew "webkit2png"
brew "wget"
brew "yarn"
brew "zopfli"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/woff2"
brew "hhvm/hhvm/hhvm"
brew "homebrew/php/php70"
brew "homebrew/php/php70-apcu"
brew "homebrew/php/php70-gmp"
brew "homebrew/php/php70-ioncubeloader"
brew "homebrew/php/php70-mcrypt"
brew "homebrew/php/php70-memcached"
brew "homebrew/php/php70-msgpack"
brew "homebrew/php/php70-opcache"
brew "homebrew/php/php70-scrypt"
brew "homebrew/php/php70-xdebug"
cask "alfred"
cask "atom"
cask "beyond-compare"
cask "debookee"
cask "dropbox"
cask "forklift"
cask "gog-galaxy"
cask "gpgtools"
cask "iterm2"
cask "java"
cask "keybase"
cask "pl2303"
cask "resilio-sync"
cask "sequel-pro"
cask "sourcetree"
cask "steam"
cask "sublime-text"
cask "teamviewer"
cask "textmate"
cask "tower"
cask "transmission"
cask "transmit"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "vmware-fusion"
cask "wireshark"
mas "Boxy", id: 1053031090
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "KakaoTalk", id: 869223134
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Remote Desktop", id: 409907375
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telegram Desktop", id: 946399090
mas "The Unarchiver", id: 425424353
mas "Tweetbot", id: 557168941
mas "Twitter", id: 409789998
mas "Xcode", id: 497799835
